import CantorAudit
import KernelCocycle
import KernelEscape
import CompletionWitness
import KernelLawfulness
import PressureExtension
import PressureRegularity
import RetainedMemory
import AffinityPressure
import MatrixPressure
import CompletionAffinityWitness

#print axioms CantorAudit.collision_obstructs_factorization
#print axioms CantorAudit.factorization_iff_constant_on_fibers
#print axioms CantorAudit.extension_with_zero_gap
#print axioms CantorAudit.coarse_collision_with_exact_factorization
#print axioms CantorAudit.conditional_fekete
#print axioms CantorAudit.linear_partition_zero_pressure
#print axioms CantorAudit.bounded_weight_sum_zero_pressure
#print axioms CantorAudit.selector_time_sum_zero
#print axioms CantorAudit.a3_arbitrarily_long_waits
#print axioms CantorAudit.a3_wait_then_return

#print axioms CantorAudit.kernelProduct_split
#print axioms CantorAudit.kernelEnvelope_submultiplicative
#print axioms CantorAudit.kernel_pressure_exists
#print axioms CantorAudit.matrix_two_step_escape
#print axioms CantorAudit.pressure_gap_of_even_escape
#print axioms CantorAudit.bounded_factor_same_pressure
#print axioms CantorAudit.witnessKernel_stochastic
#print axioms CantorAudit.witnessFullCompletion_saturates
#print axioms CantorAudit.witnessSingleton_unique
#print axioms CantorAudit.witness_package_extension
#print axioms CantorAudit.witness_pair_lumpability_obstruction
#print axioms CantorAudit.witnessFullCompletion_formula
#print axioms CantorAudit.witnessSingletonCompletion_formula

#print axioms CantorAudit.noiseNormalizedRow_stochastic
#print axioms CantorAudit.minorizedRow_stochastic
#print axioms CantorAudit.minorizedRow_positive
#print axioms CantorAudit.normalized_coordinate_difference
#print axioms CantorAudit.clamped_interval
#print axioms CantorAudit.transpose_historyTotal
#print axioms CantorAudit.pressureKernelChoice_stochastic
#print axioms CantorAudit.pressureKernelChoice_uniform
#print axioms CantorAudit.pressureCompletion_formula
#print axioms CantorAudit.pressureFixed_stationary
#print axioms CantorAudit.pressureCompletion_positive
#print axioms CantorAudit.pressureFixed_unique
#print axioms CantorAudit.pressureBase_equal
#print axioms CantorAudit.pressure_profile_extension
#print axioms CantorAudit.pressure_lipschitz
#print axioms CantorAudit.pressure_strictAnti
#print axioms CantorAudit.pressure_unique_zero
#print axioms CantorAudit.completion_stationary_ratio
#print axioms CantorAudit.retained_prototype_split
#print axioms CantorAudit.midpoint_noise_recouples
#print axioms CantorAudit.affinity_row_loss
#print axioms CantorAudit.sqrt_affinity_row_loss
#print axioms CantorAudit.matrixPathValue_upper
#print axioms CantorAudit.matrix_partition_exponential_loss
#print axioms CantorAudit.pressure_upper_of_exponential

#print axioms CantorAudit.positiveMatrix_row_le_norm
#print axioms CantorAudit.positiveMatrix_norm_le
#print axioms CantorAudit.matrixHistory_nonnegative
#print axioms CantorAudit.matrixHistory_rows
#print axioms CantorAudit.matrix_pressure_exists
#print axioms CantorAudit.constant_matrixHistoryEnvelope
#print axioms CantorAudit.matrixPathValue_eq_row
#print axioms CantorAudit.positiveMatrixPartition_bounds
#print axioms CantorAudit.positiveMatrixPartition_pressure_exists
#print axioms CantorAudit.finite_positive_matrix_bounds
#print axioms CantorAudit.matrixPathValue_positive
#print axioms CantorAudit.positiveMatrixPartition_positive
#print axioms CantorAudit.positiveMatrixPartition_pressure_exists_of_positive
#print axioms CantorAudit.affinity_pressure_exists_strict
#print axioms CantorAudit.stochasticMatrix_pressure_zero
#print axioms CantorAudit.affinityMatrix_self
#print axioms CantorAudit.weighted_affinity_pressure_gap
#print axioms CantorAudit.pressureFixed_positive
#print axioms CantorAudit.pressureCompletion_stochastic
#print axioms CantorAudit.pressurePredictor_positive
#print axioms CantorAudit.pressurePredictor_stochastic
#print axioms CantorAudit.pressurePredictor_loss
#print axioms CantorAudit.completedInitial_stationary
#print axioms CantorAudit.completion_affinity_witness_gap
#print axioms CantorAudit.completion_reference_pressure_zero
