import CantorAudit
import KernelCocycle
import KernelEscape
import CompletionWitness
import KernelLawfulness
import PressureExtension
import PressureRegularity
import RetainedMemory
import AffinityPressure
import MatrixPressure
import CompletionAffinityWitness
import CompletionDynamics
import CompletionForcing
import ConditionalPressure
import OriginalShell
import PrimitiveCompletion
import HistoryConditioning
import LoopExtension
import SparsePressure
import ControlledShell
import PackagedDisintegration
import ReferencePressure
import WeightedHistoryBounds

#print axioms CantorAudit.collision_obstructs_factorization
#print axioms CantorAudit.factorization_iff_constant_on_fibers
#print axioms CantorAudit.extension_with_zero_gap
#print axioms CantorAudit.coarse_collision_with_exact_factorization
#print axioms CantorAudit.conditional_fekete
#print axioms CantorAudit.linear_partition_zero_pressure
#print axioms CantorAudit.bounded_weight_sum_zero_pressure
#print axioms CantorAudit.selector_time_sum_zero
#print axioms CantorAudit.a3_arbitrarily_long_waits
#print axioms CantorAudit.a3_wait_then_return

#print axioms CantorAudit.kernelProduct_split
#print axioms CantorAudit.kernelEnvelope_submultiplicative
#print axioms CantorAudit.kernel_pressure_exists
#print axioms CantorAudit.matrix_two_step_escape
#print axioms CantorAudit.pressure_gap_of_even_escape
#print axioms CantorAudit.bounded_factor_same_pressure
#print axioms CantorAudit.witnessKernel_stochastic
#print axioms CantorAudit.witnessFullCompletion_saturates
#print axioms CantorAudit.witnessSingleton_unique
#print axioms CantorAudit.witness_package_extension
#print axioms CantorAudit.witness_pair_lumpability_obstruction
#print axioms CantorAudit.witnessFullCompletion_formula
#print axioms CantorAudit.witnessSingletonCompletion_formula

#print axioms CantorAudit.noiseNormalizedRow_stochastic
#print axioms CantorAudit.minorizedRow_stochastic
#print axioms CantorAudit.minorizedRow_positive
#print axioms CantorAudit.normalized_coordinate_difference
#print axioms CantorAudit.clamped_interval
#print axioms CantorAudit.transpose_historyTotal
#print axioms CantorAudit.pressureKernelChoice_stochastic
#print axioms CantorAudit.pressureKernelChoice_uniform
#print axioms CantorAudit.pressureCompletion_formula
#print axioms CantorAudit.pressureFixed_stationary
#print axioms CantorAudit.pressureCompletion_positive
#print axioms CantorAudit.pressureFixed_unique
#print axioms CantorAudit.pressureBase_equal
#print axioms CantorAudit.pressure_profile_extension
#print axioms CantorAudit.pressure_lipschitz
#print axioms CantorAudit.pressure_strictAnti
#print axioms CantorAudit.pressure_unique_zero
#print axioms CantorAudit.completion_stationary_ratio
#print axioms CantorAudit.retained_prototype_split
#print axioms CantorAudit.midpoint_noise_recouples
#print axioms CantorAudit.affinity_row_loss
#print axioms CantorAudit.sqrt_affinity_row_loss
#print axioms CantorAudit.matrixPathValue_upper
#print axioms CantorAudit.matrix_partition_exponential_loss
#print axioms CantorAudit.pressure_upper_of_exponential

#print axioms CantorAudit.positiveMatrix_row_le_norm
#print axioms CantorAudit.positiveMatrix_norm_le
#print axioms CantorAudit.matrixHistory_nonnegative
#print axioms CantorAudit.matrixHistory_rows
#print axioms CantorAudit.matrix_pressure_exists
#print axioms CantorAudit.constant_matrixHistoryEnvelope
#print axioms CantorAudit.matrixPathValue_eq_row
#print axioms CantorAudit.positiveMatrixPartition_bounds
#print axioms CantorAudit.positiveMatrixPartition_pressure_exists
#print axioms CantorAudit.finite_positive_matrix_bounds
#print axioms CantorAudit.matrixPathValue_positive
#print axioms CantorAudit.positiveMatrixPartition_positive
#print axioms CantorAudit.positiveMatrixPartition_pressure_exists_of_positive
#print axioms CantorAudit.affinity_pressure_exists_strict
#print axioms CantorAudit.stochasticMatrix_pressure_zero
#print axioms CantorAudit.affinityMatrix_self
#print axioms CantorAudit.weighted_affinity_pressure_gap
#print axioms CantorAudit.pressureFixed_positive
#print axioms CantorAudit.pressureCompletion_stochastic
#print axioms CantorAudit.pressurePredictor_positive
#print axioms CantorAudit.pressurePredictor_stochastic
#print axioms CantorAudit.pressurePredictor_loss
#print axioms CantorAudit.completedInitial_stationary
#print axioms CantorAudit.completion_affinity_witness_gap
#print axioms CantorAudit.completion_reference_pressure_zero

#print axioms CantorAudit.completionIterate_mass
#print axioms CantorAudit.stochastic_zero_mass_contraction
#print axioms CantorAudit.completionIterate_error
#print axioms CantorAudit.completionIterate_converges
#print axioms CantorAudit.completion_fixed_unique
#print axioms CantorAudit.completion_stationary_error_of_residual
#print axioms CantorAudit.pressureTransport_stochastic
#print axioms CantorAudit.pressureSpectralCompletion_formula
#print axioms CantorAudit.forcedCompletedFixed_mass
#print axioms CantorAudit.auditCompletedChannel_floor
#print axioms CantorAudit.audit_completion_saturates
#print axioms CantorAudit.audit_completion_unique_real
#print axioms CantorAudit.forced_completion_saturates
#print axioms CantorAudit.forced_completion_fixed
#print axioms CantorAudit.forcing_produces_new_fixed_object
#print axioms CantorAudit.forcedStrataFamily_split
#print axioms CantorAudit.completion_refinement_family_extension
#print axioms CantorAudit.final_forced_readout_factorizes
#print axioms CantorAudit.audit_transport_macro_obstruction
#print axioms CantorAudit.saturation_and_material_forcing_support

#print axioms CantorAudit.initial_conditioning_common_pressure
#print axioms CantorAudit.binary_disintegration_pressure
#print axioms CantorAudit.binary_disintegration_gap_positive_iff
#print axioms CantorAudit.initial_conditioning_disintegration
#print axioms CantorAudit.equal_conditional_pressures_gap_zero
#print axioms CantorAudit.initial_conditioning_gap_zero
#print axioms CantorAudit.initial_conditioning_profiles_equal
#print axioms CantorAudit.originalBranchMatrix_rows
#print axioms CantorAudit.constant_row_partition
#print axioms CantorAudit.completion_strictness_with_equal_original_partitions
#print axioms CantorAudit.originalParameterizedMatrix_positive
#print axioms CantorAudit.original_uniform_partitions_equal
#print axioms CantorAudit.strict_completion_with_common_original_pressure
#print axioms CantorAudit.originalPackageInitial_probability
#print axioms CantorAudit.original_strict_completion_zero_gap
#print axioms CantorAudit.uniformShell_selector_and_eta_bounds
#print axioms CantorAudit.uniformShellVariation_cap
#print axioms CantorAudit.uniformShellTimescale_exit

#print axioms CantorAudit.completionIterate_nonnegative
#print axioms CantorAudit.completionIterate_succ_initial
#print axioms CantorAudit.completionIterate_distance
#print axioms CantorAudit.positive_completion_stationary_exists
#print axioms CantorAudit.completionIterate_eq_vecMul
#print axioms CantorAudit.completionIterate_add
#print axioms CantorAudit.completionIterate_pow
#print axioms CantorAudit.completionIterate_fixed
#print axioms CantorAudit.stochastic_power_rows
#print axioms CantorAudit.primitive_completion_error
#print axioms CantorAudit.primitive_completion_saturates
#print axioms CantorAudit.primitive_completion_unique
#print axioms CantorAudit.primitive_completion_stationary_error
#print axioms CantorAudit.completionIterate_positive_columns
#print axioms CantorAudit.nonnegative_matrix_product
#print axioms CantorAudit.stochastic_matrix_product
#print axioms CantorAudit.prototype_lift_retains_transport
#print axioms CantorAudit.matrix_power_domination
#print axioms CantorAudit.primitive_transport_completion_saturates
#print axioms CantorAudit.matrix_power_positive_of_path
#print axioms CantorAudit.primitive_completion_readout_factorizes
#print axioms CantorAudit.completionLimitClosure_idempotent
#print axioms CantorAudit.completionLimitClosure_absorbs
#print axioms CantorAudit.primitive_completion_idempotent_limit
#print axioms CantorAudit.full_support_history_bounds
#print axioms CantorAudit.full_support_history_same_pressure
#print axioms CantorAudit.scalar_row_history
#print axioms CantorAudit.stochastic_cocycle_initial_law_independent
#print axioms CantorAudit.equal_rows_mul_rankOne
#print axioms CantorAudit.equal_rows_norm
#print axioms CantorAudit.joinedHistory_equal_from_two
#print axioms CantorAudit.joinedHistory_rows_equal
#print axioms CantorAudit.joinedHistory_norms_equal
#print axioms CantorAudit.joinedHistory_partitions_equal
#print axioms CantorAudit.joinedHistory_disintegration_equal
#print axioms CantorAudit.stochastic_row_entry_bound
#print axioms CantorAudit.sparseSelectorMatrix_nonnegative
#print axioms CantorAudit.sparseSelectorMatrix_row_bounds
#print axioms CantorAudit.sparse_selector_pressure_exists
#print axioms CantorAudit.sparseSelectorMatrix_parameter_bound
#print axioms CantorAudit.moving_history_scaled_domination
#print axioms CantorAudit.moving_envelope_scaled_domination
#print axioms CantorAudit.pressure_comparison_of_scaling
#print axioms CantorAudit.sparse_selector_pressure_parameter_bound
#print axioms CantorAudit.sparse_selector_pressure_strictAnti
#print axioms CantorAudit.sparse_selector_pressure_at_one
#print axioms CantorAudit.original_selector_observable_bounds
#print axioms CantorAudit.original_budget_core_survives_noise
#print axioms CantorAudit.original_branch_root_anchor
#print axioms CantorAudit.supported_difference_mul_common_rows
#print axioms CantorAudit.matchedHistory_equal_from_two
#print axioms CantorAudit.matchedHistory_norms_equal
#print axioms CantorAudit.matchedHistory_partitions_equal
#print axioms CantorAudit.normalized_target_control
#print axioms CantorAudit.controlledTimescale_step_bound
#print axioms CantorAudit.controlledTimescale_switch_reset
#print axioms CantorAudit.controlledBudget_preserved
#print axioms CantorAudit.controlledBudget_increases_before_cap
#print axioms CantorAudit.controlled_shell_all_iterates
#print axioms CantorAudit.controlled_shell_root_anchor
#print axioms CantorAudit.controlled_shell_pressure_root
#print axioms CantorAudit.binary_equal_weight_gap
#print axioms CantorAudit.separated_original_continuations_gap_bound
#print axioms CantorAudit.binary_actual_package_mass
#print axioms CantorAudit.binary_actual_package_conditional
#print axioms CantorAudit.binary_actual_package_disintegration
#print axioms CantorAudit.binary_package_nonfactor
#print axioms CantorAudit.binary_actual_package_pressure
#print axioms CantorAudit.reference_pressure_of_arbitrary_small_loss
#print axioms CantorAudit.reference_pressure_of_dense_component_bounds
#print axioms CantorAudit.pressure_bounds_of_geometric_constants
#print axioms CantorAudit.binary_gap_lower_of_pressure_intervals
#print axioms CantorAudit.binary_actual_package_pressure_from_intervals
#print axioms CantorAudit.weighted_matrixHistory_bounds
#print axioms CantorAudit.weighted_matrixHistory_norm_bounds
